from fpdf import FPDF
from datetime import datetime
import os

def generate_health_report(user_input, response, age_group, language):
    """Generate a professional PDF health report"""
    try:
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 20)
        pdf.cell(0, 15, "Health Education Report", ln=True, align="C")
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
        pdf.cell(0, 10, f"Age Group: {age_group} | Language: {language}", ln=True)
        pdf.ln(10)
        
        # User Question
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Your Question:", ln=True)
        pdf.set_font("Arial", "", 12)
        pdf.multi_cell(0, 8, user_input[:500])
        pdf.ln(5)
        
        # Response (limited to 1000 chars for PDF)
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Health Information:", ln=True)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 7, response[:2000])
        pdf.ln(5)
        
        # Disclaimer
        pdf.set_font("Arial", "I", 8)
        pdf.multi_cell(0, 5, "⚠️ This is educational information only. Always consult a healthcare professional for medical advice, diagnosis, or treatment.")
        
        # Footer
        pdf.set_y(-20)
        pdf.set_font("Arial", "I", 8)
        pdf.cell(0, 10, "Generated by Symptom Education Assistant", ln=True, align="C")
        
        filename = f"health_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        pdf.output(filename)
        return filename
    except Exception as e:
        print(f"PDF Error: {e}")
        return None