
from fpdf import FPDF
from datetime import datetime


def clean_pdf_text(text):
    """Remove characters that the built-in FPDF Arial font cannot encode."""
    if not text:
        return ""

    text = str(text)

    replacements = {
        "⚠️": "WARNING:",
        "🩺": "",
        "—": "-",
        "–": "-",
        "-": "-",
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "…": "...",
        "\u00a0": " ",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    # Keep only characters supported by FPDF's built-in fonts
    text = text.encode("latin-1", "replace").decode("latin-1")

    return text


def generate_health_report(user_input, response, age_group, language):
    """Generate a professional PDF health report."""
    try:
        pdf = FPDF()
        pdf.add_page()

        # Header
        pdf.set_font("Arial", "B", 20)
        pdf.cell(
            0,
            15,
            "Health Education Report",
            ln=True,
            align="C"
        )

        pdf.set_font("Arial", "I", 10)
        pdf.cell(
            0,
            10,
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            ln=True
        )

        pdf.cell(
            0,
            10,
            clean_pdf_text(
                f"Age Group: {age_group} | Language: {language}"
            ),
            ln=True
        )

        pdf.ln(10)

        # User Question
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Your Question:", ln=True)

        pdf.set_font("Arial", "", 12)
        pdf.multi_cell(
            0,
            8,
            clean_pdf_text(user_input[:500])
        )

        pdf.ln(5)

        # Health Response
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Health Information:", ln=True)

        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(
            0,
            7,
            clean_pdf_text(response[:2000])
        )

        pdf.ln(5)

        # Disclaimer
        pdf.set_font("Arial", "I", 8)
        pdf.multi_cell(
            0,
            5,
            clean_pdf_text(
                "WARNING: This is educational information only. "
                "Always consult a healthcare professional for medical "
                "advice, diagnosis, or treatment."
            )
        )

        # Footer
        pdf.set_y(-20)
        pdf.set_font("Arial", "I", 8)
        pdf.cell(
            0,
            10,
            "Generated by Symptom Education Assistant",
            ln=True,
            align="C"
        )

        filename = (
            f"health_report_"
            f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        )

        pdf.output(filename)

        return filename

    except Exception as e:
        print(f"PDF Error: {e}")
        return None
